name: Smoke Test for FFI

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  smoke_test_ffi:
    strategy:
      matrix:
        ruby: [ "3.3" ]
        # macos-14 is ARM-based
        # macos-14-large is x86-based
        # ubuntu-latest (x86) is not included because the full test suite runs on it
        os: [ macos-14, macos-14-large, ubuntu-22.04-arm ]

    runs-on: ${{ matrix.os }}

    # Allows all jobs to run even if one fails
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4
      - name: Set up the correct Gemfile for Ruby ${{ matrix.ruby }}
        run: bin/link_gemfile "${{ matrix.ruby }}"
      # Lock files are generated for a specific platform
      - run: rm Gemfile.lock
      - name: Install system dependencies
        if: runner.os == 'macOS'
        run: |
          brew install mysql postgresql
          bundle config set build.mysql2 --with-opt-dir=$(brew --prefix zstd)
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: "sudo apt-get update && sudo apt-get install libmysqlclient-dev libpq-dev libcurl4-openssl-dev"
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Download libzen
        run: "bundle exec rake libzen:download:current"
      - name: Run the smoke tests
        run: DISABLE_COVERAGE=true ruby -Ilib:test test/aikido/zen/scanners/sql_injection_scanner_test.rb
